project_id = "central-ti"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[db.pooler]
default_pool_size = 15
max_client_conn = 200

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []

[auth.email]
double_confirm_changes = false
enable_confirmations = false
max_frequency = "1m0s"
otp_length = 6

[auth.email.smtp]
enabled = true
host = "smtp.resend.com"
port = 587
user = "resend"
pass = "env(RESEND_SMTP_PASS)"
admin_email = "helpdeskti@madeirasgasometro.com.br"
sender_name = "TI Gasômetro Madeiras"

[auth.email.template.recovery]
subject = "Recuperação de senha — TI Gasômetro Madeiras"
content_path = "./supabase/templates/recovery.html"

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[storage.analytics]
enabled = true
max_namespaces = 10

[storage.image_transformation]
enabled = true
